spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/flat_rent
    username: postgres
    password: 1111
    driver: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: update
      #ddl-auto: update создает таблицы если не существует, дополняет существующие таблицы колонками
      #ddl-auto: create - удаляет перед созданием существующие таблицы, создает новые
      #ddl-auto: create-drop - тоже что и create + при окончании работы приложения удаляет существующие таблицы
      #ddl-auto: none - не будет создавать, удалять, изменять сущности(таблицы, сиквенсы, констрейнты) в бд
      #ddl-auto: validate - она проверяет соответствие сущности в java с структурой бд
    show-sql: true #Отображение sql запросов, который генерирует Hibernate или JPA
    properties:
      hibernate:
        format_sql: true #Форматирование запросов (красивое отображение)
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE